### PR TITLE
Implemented logic to exclude certain file extensions from being redirected to S3

### PR DESCRIPTION
**Pull request by z342li**

### CODE REVIEW

**Comment by jamesdobson** [comment]
@dtretyakov any update on when this can be merged?

**Comment by dtretyakov** [comment]
@z342li, @jamesdobson could you please describe what is your use case or which problem you're trying to address?

**Comment by jamesdobson** [comment]
@dtretyakov see, for example, a ticket such as https://youtrack.jetbrains.com/issue/TW-57705 where another user has the same problem we have.

Basically, HTML (and others like CSS) can contain links to other build artifacts. For example, some software that we run in our builds produces HTML reports with links to other reports, images, etc. But our builds also produce large binary artifacts. We want to redirect to S3 for most artifacts to off-load those requests from the TeamCity server; but we want the TeamCity server to handle requests for artifacts that can contain links to other artifacts, so that the outgoing links also work.

Zipping such a report & all dependencies hasn't been a good solution for our use case, either.

**Comment by dtretyakov** [comment]
@jamesdobson, thanks for the details. So your use pattern looks like as follows?
1. Open build artifacts tab.
2. Click on html report file to view it.

Did you try [configuring report tabs](https://www.youtube.com/watch?v=Z4gFJN_UmsQ) for your build configuration?

**Comment by jamesdobson** [comment]
@dtretyakov we have several use cases. One is the one you describe, the other is:
1. Click on a report tab to see a "summary" report that links to 50 other reports
2. Click on a link in the "summary" report to view another report

Another use case we have is external links from our test status dashboard. Each of the 50 tests is reported to a separate widget on the dashboard. Clicking on the widget takes the browser to the html artifact for that report's main page, which then links to other build artifacts like PNG images, etc.

We have tried several different possibilities, including zip files, and worked with JetBrains support; none of the built-in features fit our use case.

**Comment by dtretyakov** [comment]
@dimyriy, could please comment on it?

**Comment by dimyriy** [comment]
We implemented this feature request in a slightly different way. Please, take a look at the https://youtrack.jetbrains.com/issue/TW-57705:

> It's possible now to configure the list of filename extensions for artifacts that should be proxied through TeamCity without redirect to external artifact storage using the parameter `teamcity.internal.externalArtifacts.artifactDownloadProcessor.disableBasedOnRequestForExtensions`. 
It's also possible to force the proxying of artifact files having certain extensions using the parameter `teamcity.internal.externalArtifacts.artifactDownloadProcessor.forciblyDisableForExtensions`.
Both parameters are comma-separated lists of strings i.e. `teamcity.internal.externalArtifacts.artifactDownloadProcessor.disableBasedOnRequestForExtensions=html,css,js`

**Pull request closed without merging**
